### ISSUE TITLE
这个文件要放在什么位置

### ISSUE THREAD

**Issue by zhenhappy** [Rongronggg9/Google-IP-Range#2]
之前有用过类似的，但是现在一下子想不起来路径是多少了

**Comment by yeahwu** [comment]
直接改名ip_range.txt
丢到 data/gaeproxy/   里面就好了

**Comment by whhxmwhh** [comment]
我也是要找这个问题。。还是谷歌了得。从谷歌找过来的。

**Comment by whhxmwhh** [comment]
刚才发现放进去之后再去扫描。会出现有效的ip直线下降。建议不要更改就用软件自带的飞快了。

**Comment by Rongronggg9** [comment]
@whhxmwhh 扫描线程不要开太大……否则导致连接成功率直线下降……
